[[redirects]]
  from = "/api/*"
  to = "https://flashcardsbackend.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/deck/*"
  to = "https://flashcardsbackend.herokuapp.com/deck/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/card/*"
  to = "https://flashcardsbackend.herokuapp.com/card/:splat"
  status = 200
  force = true