export const HOME = "/"
export const SECRET = "/secret"
export const LOGIN = "/login"
export const VERIFY_EMAIL = "/verify-email"
export const PROFILE = "/profile"
export const SETTINGS = "/settings"
export const ACCOUNT_DELETED = "/account-deleted"
export const DECK = "/deck"
